name: hongik_ingan
description: "널리 홍대생들을 이롭게 하라"
publish_to: 'none'

version: 1.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  dio_cookie_manager: ^3.4.0
  flutter_secure_storage: ^10.0.0
  cookie_jar: ^4.0.9
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.15
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    # 테스트용 assets
    - path: assets/test/js/
      flavors:
        - dev
    - path: assets/test/fonts/
      flavors:
        - dev
    - path: assets/test/css/
      flavors:
        - dev

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/images/icon.png"