name: hongik_ingan
description: "널리 홍대생들을 이롭게 하라"
publish_to: 'none'

version: 1.3.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.11.0
  dio_cookie_manager: ^3.5.0
  flutter_secure_storage: ^10.3.1
  cookie_jar: ^4.0.9
  charset: ^2.0.1
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2
  logger: ^2.7.0
  share_plus: ^13.3.0
  geolocator: ^14.0.3
  html: ^0.15.6
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon_foreground.png
    # 테스트용 assets
    - path: assets/test/js/
      flavors:
        - dev
    - path: assets/test/fonts/
      flavors:
        - dev
    - path: assets/test/css/
      flavors:
        - dev
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Ui.ttf
          weight: 400

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon_full.png"
  adaptive_icon_background: "#05014A"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"
